application/config/routes.rb
# frozen_string_literal: true

require 'karafka/web'

Rails.application.routes.draw do
  root 'main#show'

  resources :visitors, only: %i[index show]
  resources :attendances, only: %i[index]

  mount Karafka::Web::App, at: '/karafka'
end

application/app/models/application_record.rb
# frozen_string_literal: true

# Rails app record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

application/app/models/attendance.rb
class Attendance < ApplicationRecord
end

application/app/models/visit.rb
# frozen_string_literal: true

# Represents a single page visit
class Visit < ApplicationRecord
  scope :recent, -> { joins(:visitor).order(visited_at: :desc).limit(20) }

  belongs_to :visitor

  def broadcast
    Karafka.producer.produce_async(
      topic: 'visits',
      payload: {
        id: id,
        visited_at: visited_at,
        visitor_id: visitor_id,
        page_path: page_path
      }.to_json
    )
  end
end

application/app/models/visitor.rb
# frozen_string_literal: true

# Represents a single website visitor
class Visitor < ApplicationRecord
  has_many :visits
end

application/app/controllers/application_controller.rb
# frozen_string_literal: true

# Main app controller
class ApplicationController < ActionController::Base
  before_action :assign_visitor_id
  before_action :track_visit

  private

  # Assigns a unique identifier to the user visiting the page, so we can track him
  def assign_visitor_id
    session[:visitor_id] ||= SecureRandom.uuid
  end

  # Async user tracking
  def track_visit
    VisitorsJob.perform_later(session[:visitor_id])

    Karafka.producer.produce_async(
      topic: 'visits',
      payload: {
        id: SecureRandom.uuid,
        visited_at: Time.zone.now,
        visitor_id: session[:visitor_id],
        page_path: request.path
      }.to_json
    )
  end
end

application/app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  def index
    @attendance = Attendance.order(created_at: :desc)
  end
end

application/app/controllers/main_controller.rb
# frozen_string_literal: true

# Main page display
class MainController < ApplicationController
  # Displays recent visits
  def show
    @recent_visits = Visit.recent
  end
end

application/app/controllers/visitors_controller.rb
# frozen_string_literal: true

# Visitors display controller
class VisitorsController < ApplicationController
  # Lists most recent visitors
  def index
    @visitors = Visitor.order(created_at: :desc)
  end

  # Shows visitor details
  def show
    @visitor = Visitor.find(params[:id])
    @visits = @visitor.visits.order(visited_at: :desc)
  end
end

application/app/helpers/application_helper.rb
# frozen_string_literal: true

# Rails app helper
module ApplicationHelper
end

application/app/views/attendances/index.html.erb
<h3>Attendance</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Created</th>
      <th>Site</th>
      <th>Entity</th>
      <th>In</th>
      <th>Out</th>
    </tr>
  </thead>
  <tbody>
    <% @attendance.each do |attendance| %>
      <tr>
        <td><%= attendance.id %></td>
        <td><%= attendance.created_at %></td>
        <td><%= attendance.site_identifier %></td>
        <td><%= attendance.entity_identifier %></td>
        <td><%= attendance.sign_in_time %></td>
        <td><%= attendance.sign_out_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Procare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Procare Platform</a>

        <div class="collapse navbar-collapse container" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= visitors_path %>">Visitors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= attendances_path %>">Attendance</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="bg-light p-5">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

application/app/views/main/show.html.erb
<h3>Recent visits</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Request id</th>
      <th>Visitor id</th>
      <th>Visited at</th>
      <th>Page path</th>
    </tr>
  </thead>
  <tbody>
    <% @recent_visits.each do |visit| %>
      <tr>
        <td><%= visit.id %></td>
        <td><%= link_to visit.visitor.id, visitor_path(visit.visitor) %></td>
        <td><%= visit.visited_at %></td>
        <td><%= visit.page_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

application/app/views/visitors/index.html.erb
<h3>Visitors</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= link_to visitor.id, visitor %></td>
        <td><%= visitor.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

application/app/views/visitors/show.html.erb
<h3>Visitor recent visits</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Request id</th>
      <th>Visited at</th>
      <th>Page path</th>
    </tr>
  </thead>
  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.id %></td>
        <td><%= visit.visited_at %></td>
        <td><%= visit.page_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>